name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.x'
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install deps
        run: |
          go mod download

      - name: Check lint
        run: |
          make lint
      - name: Check tests
        run: |
          make test

      - name: Build binary
        run: |
          make build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dmp-reqcheck-linux-x64.zip
          path: bin/dmp-reqcheck
          if-no-files-found: error
